INSERT INTO clothes (id, name, color, size, price, available_quantity)
VALUES
(nextval('clothes_seq'), 'T-shirt', 'Red', 'M', 19.99, 10),
(nextval('clothes_seq'), 'Jeans', 'Blue', 'L', 49.99, 15),
(nextval('clothes_seq'), 'Jacket', 'Black', 'XL', 99.99, 5),
(nextval('clothes_seq'), 'Hat', 'Green', 'S', 14.99, 20),
(nextval('clothes_seq'), 'Shoes', 'White', 'XL', 59.99, 8),
(nextval('clothes_seq'), 'Socks', 'Black', 'M', 5.99, 30),
(nextval('clothes_seq'), 'Sweater', 'Gray', 'L', 39.99, 12),
(nextval('clothes_seq'), 'Shorts', 'Beige', 'S', 24.99, 18),
(nextval('clothes_seq'), 'Scarf', 'Red', 'L', 15.99, 25),
(nextval('clothes_seq'), 'Gloves', 'Black', 'M', 19.99, 10),
(nextval('clothes_seq'), 'Boots', 'Brown', 'M', 89.99, 6),
(nextval('clothes_seq'), 'Blazer', 'Blue', 'M', 119.99, 3),
(nextval('clothes_seq'), 'Dress', 'Pink', 'S', 69.99, 7),
(nextval('clothes_seq'), 'Sweatpants', 'Black', 'L', 29.99, 11),
(nextval('clothes_seq'), 'Tank Top', 'White', 'M', 14.99, 17),
(nextval('clothes_seq'), 'Pants', 'Gray', 'XL', 39.99, 9),
(nextval('clothes_seq'), 'Raincoat', 'Yellow', 'M', 89.99, 4),
(nextval('clothes_seq'), 'Pullover', 'Navy', 'S', 29.99, 22),
(nextval('clothes_seq'), 'Cardigan', 'Green', 'L', 44.99, 14),
(nextval('clothes_seq'), 'Tracksuit', 'Black', 'XL', 79.99, 5),
(nextval('clothes_seq'), 'Polo', 'Blue', 'M', 39.99, 10),
(nextval('clothes_seq'), 'Windbreaker', 'Orange', 'L', 49.99, 8),
(nextval('clothes_seq'), 'Swimwear', 'Yellow', 'S', 25.99, 16),
(nextval('clothes_seq'), 'Vest', 'Black', 'M', 19.99, 18),
(nextval('clothes_seq'), 'Overalls', 'Denim', 'L', 69.99, 2),
(nextval('clothes_seq'), 'Cap', 'Gray', 'L', 12.99, 26),
(nextval('clothes_seq'), 'Blouse', 'White', 'S', 34.99, 13),
(nextval('clothes_seq'), 'Cargos', 'Green', 'XL', 54.99, 11),
(nextval('clothes_seq'), 'Jumpsuit', 'Black', 'M', 89.99, 4),
(nextval('clothes_seq'), 'Thermal Shirt', 'Blue', 'L', 29.99, 19);