server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clothes-service
          uri: lb:http://CLOTHES-SERVICE
          predicates:
            - Path=/api/v1/clothes/**

