server:
  port: 8020
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ms_pg_sql:5434/order
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  kafka:
#    producer:
#      bootstrap-server: ms_kafka:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.type.mapping: orderConfirmation:ru.Harevich.order.kafka.OrderConfirmation
application:
  config:
    clothes-url: http://gateway:8222/api/v1/clothes
    order-url: http://gateway:8222/api/v1/orders

